### ISSUE TITLE
new-if-then

### ISSUE THREAD

**Issue by Austin5769** [rfkay3/SPCompiler#11]
We must implement if-then statements into our compiler
Grammar implementation:
- [x] if 
- [x] then
- [x] else 
- [ ] else if
- [ ] and
- [ ] or 

nuances 
the brackets of an if-then statement are replaced I with begin and end 
if-then statements will not appear in an after a var
will only appear in the body of the program after 
MUST be able to nest if statements

An if-then statement can be followed by an optional else if-then-else statement, which is very useful to test various conditions using single if-then-else if statement.
if() then
else if() then
else

An if-then statement can have zero or one else's and it must come after any else if's.
An if-then statement can have zero to many else if's and they must come before the else.
Once an else if succeeds, none of the remaining else if's or else's will be tested.
No semicolon (;) is given before the last else keyword, but all statements can be compound statements.

example of legal grammar:<br>
If a < b AND c = d or b < > c then

**Comment by hunterlj** [comment]
Creating a new Class to implement all of if then statements and corresponding blocks
